name: deploy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  # Build job
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: github-pages
    - name: Extract Artifact
      run: ls -l
      
