name: deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  # Build job
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: deploy.yml
        workflow_conclusion: success
        name: github-pages
    - name: Extract Artifact
      run: |
        tar -xvzf artifact.tar
        ls -l
