name: deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  # Build job
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
    - name: Extract Artifact
      run: |
        pwd
        cd /etc/usr/artifacts
        ls -l
      
